'use client'

import Link from 'next/link'
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

import { ScenarioActionCenter } from '@/components/ScenarioActionCenter'
import { useDefaultAccountContext } from '@/lib/account-context'
import { useDebounce } from '@/lib/hooks'
import {
  analyzeChannels,
  listScenarios,
  recommendScenario,
  saveScenario,
  ScenarioRecordPayload,
  TargetCpaOverridePayload,
} from '@/lib/api'
import type {
  ChannelMetrics,
  ScenarioPlan,
} from '@/types'
import {
  DEFAULT_TARGET_CPA,
  DEFAULT_BUDGET_DELTA_PERCENT,
  mapApiToChannelMetrics,
  formatTargetCpaInput,
  buildChannelTargetMap,
  buildChannelTargetDrafts,
  buildChannelTargetDraftsFromMap,
  buildChannelTargetOverrides,
  mapScenarioPlan,
  applyRecommendationConfidence,
  serializeScenarioPlan,
  readScenarioPlan,
  readScenarioTargetOverrides,
  formatMoney,
  sanitizeFileName,
  downloadFile,
  escapeCsv,
  buildNextActionSummary,
} from '@/lib/scenario-helpers'

// ---------------------------------------------------------------------------
// localStorage keys
// ---------------------------------------------------------------------------

const LS_TARGET_CPA = 'budgetradar_target_cpa'
const LS_CHANNEL_OVERRIDES = 'budgetradar_channel_target_overrides'

// ---------------------------------------------------------------------------
// Plan Page
// ---------------------------------------------------------------------------

export default function PlanPage() {
  // ---- Account context ----
  const {
    accountId,
    accountName,
    loading: accountLoading,
    error: accountError,
  } = useDefaultAccountContext()

  // ---- Target CPA (read from localStorage, shared with dashboard) ----
  const [targetCpa, setTargetCpa] = useState<number>(() => {
    if (typeof window === 'undefined') return DEFAULT_TARGET_CPA
    const stored = localStorage.getItem(LS_TARGET_CPA)
    return stored ? Number(stored) || DEFAULT_TARGET_CPA : DEFAULT_TARGET_CPA
  })
  const debouncedTargetCpa = useDebounce(targetCpa, 500)

  useEffect(() => {
    localStorage.setItem(LS_TARGET_CPA, String(targetCpa))
  }, [targetCpa])

  // ---- Channel data (re-fetched on mount) ----
  const [channels, setChannels] = useState<ChannelMetrics[]>([])
  const [appliedChannelTargets, setAppliedChannelTargets] = useState<Record<string, number>>({})
  const [targetCpaDrafts, setTargetCpaDrafts] = useState<Record<string, string>>({})
  const [targetCpaApplying, setTargetCpaApplying] = useState(false)
  const [targetCpaError, setTargetCpaError] = useState<string | null>(null)
  const [analysisLoading, setAnalysisLoading] = useState(false)
  const [analysisError, setAnalysisError] = useState<string | null>(null)

  // ---- Scenario planner state ----
  const [budgetDeltaPercent, setBudgetDeltaPercent] = useState(DEFAULT_BUDGET_DELTA_PERCENT)
  const [lockedChannels, setLockedChannels] = useState<string[]>([])
  const [scenarioPlan, setScenarioPlan] = useState<ScenarioPlan | null>(null)
  const [scenarioLoading, setScenarioLoading] = useState(false)
  const [scenarioSaving, setScenarioSaving] = useState(false)
  const [saveConfirmation, setSaveConfirmation] = useState<string | null>(null)
  const [scenarioError, setScenarioError] = useState<string | null>(null)
  const [scenarioName, setScenarioName] = useState('')
  const [savedScenarios, setSavedScenarios] = useState<ScenarioRecordPayload[]>([])
  const [selectedScenarioId, setSelectedScenarioId] = useState('')

  const autoGeneratedScenarioAccount = useRef<string | null>(null)

  // ---- Load saved scenarios ----
  const loadSavedScenarios = useCallback(
    async (preferredId?: string) => {
      if (!accountId) {
        return
      }

      try {
        const response = await listScenarios(accountId)
        setSavedScenarios(response.scenarios)

        if (preferredId) {
          setSelectedScenarioId(preferredId)
        }
      } catch (err) {
        setScenarioError(err instanceof Error ? err.message : 'Failed to load saved scenarios')
      }
    },
    [accountId]
  )

  // ---- Fetch channel data ----
  useEffect(() => {
    if (!accountId) {
      setChannels([])
      setAppliedChannelTargets({})
      setTargetCpaDrafts({})
      setTargetCpaError(null)
      setAnalysisError(null)
      return
    }

    const resolvedAccountId: string = accountId

    async function fetchData() {
      try {
        setAnalysisLoading(true)

        // Read stored channel target overrides
        let storedOverrides: TargetCpaOverridePayload[] = []
        try {
          const raw = localStorage.getItem(LS_CHANNEL_OVERRIDES)
          if (raw) {
            const parsed = JSON.parse(raw)
            if (Array.isArray(parsed)) {
              storedOverrides = parsed.filter(
                (o: unknown) =>
                  typeof o === 'object'
                  && o !== null
                  && 'entity_type' in o
                  && 'entity_key' in o
                  && 'target_cpa' in o
              )
            }
          }
        } catch {
          // ignore malformed localStorage
        }

        const response = await analyzeChannels(
          resolvedAccountId,
          debouncedTargetCpa,
          storedOverrides.length > 0 ? storedOverrides : undefined
        )
        const mappedChannels = response.channels.map(mapApiToChannelMetrics)
        setChannels(mappedChannels)
        setAppliedChannelTargets(buildChannelTargetMap(mappedChannels))
        setTargetCpaDrafts(buildChannelTargetDrafts(mappedChannels))
        setTargetCpaError(null)
        setAnalysisError(null)
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Failed to load data'
        const isNoData =
          message.includes('No daily_metrics')
          || message.includes('no channels')
          || message.includes('Not Found')
          || message.includes('404')
        if (isNoData) {
          setChannels([])
          setAnalysisError(null)
        } else {
          setAnalysisError(message)
        }
      } finally {
        setAnalysisLoading(false)
      }
    }

    void fetchData()
  }, [accountId, debouncedTargetCpa])

  // ---- Reset on account change ----
  useEffect(() => {
    if (!accountId) {
      setAppliedChannelTargets({})
      setTargetCpaDrafts({})
      setTargetCpaError(null)
      setSavedScenarios([])
      setScenarioPlan(null)
      setSelectedScenarioId('')
      setScenarioName('')
      setScenarioError(null)
      setBudgetDeltaPercent(DEFAULT_BUDGET_DELTA_PERCENT)
      setLockedChannels([])
      autoGeneratedScenarioAccount.current = null
      return
    }

    setScenarioPlan(null)
    setSelectedScenarioId('')
    setScenarioName('')
    setScenarioError(null)
    autoGeneratedScenarioAccount.current = null
    void loadSavedScenarios()
  }, [accountId, loadSavedScenarios])

  // ---- Sync locked channels with available channels ----
  useEffect(() => {
    const activeChannels = new Set(channels.map((channel) => channel.channelName))
    setLockedChannels((previous) => previous.filter((channelName) => activeChannels.has(channelName)))
    setAppliedChannelTargets((previous) => {
      const next: Record<string, number> = {}
      for (const channel of channels) {
        next[channel.channelName] = previous[channel.channelName] ?? channel.targetCpa
      }
      return next
    })
    setTargetCpaDrafts((previous) => {
      const next: Record<string, string> = {}
      for (const channel of channels) {
        next[channel.channelName] = previous[channel.channelName] ?? formatTargetCpaInput(channel.targetCpa)
      }
      return next
    })
  }, [channels])

  // ---- Scenario generation ----
  const runScenarioGeneration = useCallback(
    async ({
      budgetDeltaPercentOverride,
      lockedChannelsOverride,
      suppressErrors = false,
    }: {
      budgetDeltaPercentOverride?: number
      lockedChannelsOverride?: string[]
      suppressErrors?: boolean
    } = {}) => {
      if (!accountId) {
        return
      }

      try {
        setScenarioLoading(true)
        const payload = await recommendScenario({
          account_id: accountId,
          target_cpa: debouncedTargetCpa,
          budget_delta_percent: budgetDeltaPercentOverride ?? budgetDeltaPercent,
          locked_channels: lockedChannelsOverride ?? lockedChannels,
          target_cpa_overrides: buildChannelTargetOverrides(appliedChannelTargets, debouncedTargetCpa),
        })

        const rawPlan = mapScenarioPlan(payload)
        const enrichedPlan = applyRecommendationConfidence(rawPlan, channels)
        setScenarioPlan(enrichedPlan)
        setScenarioName(enrichedPlan.scenarioName)
        setSelectedScenarioId('')
        setScenarioError(null)
      } catch (err) {
        if (!suppressErrors) {
          setScenarioError(err instanceof Error ? err.message : 'Failed to generate scenario')
        }
      } finally {
        setScenarioLoading(false)
      }
    },
    [accountId, appliedChannelTargets, budgetDeltaPercent, channels, debouncedTargetCpa, lockedChannels]
  )

  // ---- Auto-generate on mount ----
  useEffect(() => {
    if (!accountId || channels.length === 0) {
      return
    }

    if (autoGeneratedScenarioAccount.current === accountId) {
      return
    }

    autoGeneratedScenarioAccount.current = accountId
    setBudgetDeltaPercent(DEFAULT_BUDGET_DELTA_PERCENT)
    void runScenarioGeneration({
      budgetDeltaPercentOverride: DEFAULT_BUDGET_DELTA_PERCENT,
      lockedChannelsOverride: [],
      suppressErrors: true,
    })
  }, [accountId, channels.length, runScenarioGeneration])

  // ---- Handlers ----

  function handleChannelTargetDraftChange(channelName: string, value: string) {
    setTargetCpaError(null)
    setTargetCpaDrafts((previous) => ({
      ...previous,
      [channelName]: value,
    }))
  }

  async function handleApplyTargetCpas() {
    if (!accountId) {
      return
    }

    const nextTargets: Record<string, number> = {}
    for (const channel of channels) {
      const rawValue = targetCpaDrafts[channel.channelName] ?? formatTargetCpaInput(channel.targetCpa)
      const parsedValue = Number(rawValue)
      if (!Number.isFinite(parsedValue) || parsedValue <= 0) {
        setTargetCpaError(`Enter a positive target CPA for ${channel.channelName}.`)
        return
      }
      nextTargets[channel.channelName] = parsedValue
    }

    try {
      setTargetCpaApplying(true)
      const overrides = buildChannelTargetOverrides(nextTargets, debouncedTargetCpa)
      const payload = await analyzeChannels(accountId, debouncedTargetCpa, overrides)
      const mappedChannels = payload.channels.map(mapApiToChannelMetrics)
      setChannels(mappedChannels)
      setAppliedChannelTargets(buildChannelTargetMap(mappedChannels))
      setTargetCpaDrafts(buildChannelTargetDrafts(mappedChannels))
      setScenarioPlan(null)
      setScenarioName('')
      setScenarioError(null)
      setAnalysisError(null)
      setTargetCpaError(null)

      // Persist channel overrides for cross-page sharing
      localStorage.setItem(LS_CHANNEL_OVERRIDES, JSON.stringify(overrides))
    } catch (err) {
      setAnalysisError(err instanceof Error ? err.message : 'Failed to apply target CPA values')
    } finally {
      setTargetCpaApplying(false)
    }
  }

  async function handleGenerateScenario() {
    await runScenarioGeneration()
  }

  async function handleSaveScenario() {
    if (!accountId || !scenarioPlan) {
      return
    }

    try {
      setScenarioSaving(true)
      const savedScenario = await saveScenario(
        accountId,
        scenarioName.trim() || scenarioPlan.scenarioName,
        serializeScenarioPlan(
          scenarioPlan,
          targetCpa,
          buildChannelTargetOverrides(appliedChannelTargets, targetCpa)
        )
      )
      setScenarioName(savedScenario.name)
      await loadSavedScenarios(savedScenario.id)
      setScenarioError(null)
      setSaveConfirmation(`Saved "${savedScenario.name}"`)
      setTimeout(() => setSaveConfirmation(null), 3000)
    } catch (err) {
      setSaveConfirmation(null)
      setScenarioError(err instanceof Error ? err.message : 'Failed to save scenario')
    } finally {
      setScenarioSaving(false)
    }
  }

  function handleToggleLockedChannel(channelName: string) {
    setLockedChannels((previous) => {
      if (previous.includes(channelName)) {
        return previous.filter((channel) => channel !== channelName)
      }

      return [...previous, channelName]
    })
  }

  function handleSelectScenario(scenarioId: string) {
    setSelectedScenarioId(scenarioId)
    if (!scenarioId) {
      return
    }

    const selectedScenario = savedScenarios.find((scenario) => scenario.id === scenarioId)
    if (!selectedScenario) {
      return
    }

    const rawPlan = readScenarioPlan(selectedScenario.budget_allocation)
    if (!rawPlan) {
      setScenarioError('Saved scenario payload is incompatible with planner view')
      return
    }

    const enrichedPlan = applyRecommendationConfidence(rawPlan, channels)
    setScenarioPlan(enrichedPlan)
    setScenarioName(selectedScenario.name)
    const scenarioOverrides = readScenarioTargetOverrides(selectedScenario.budget_allocation)
    if (channels.length > 0) {
      const nextTargets = buildChannelTargetMap(channels)
      const channelLookup = new Map(
        channels.map((channel) => [channel.channelName.toLowerCase(), channel.channelName] as const)
      )
      for (const override of scenarioOverrides) {
        if (override.entity_type !== 'channel') {
          continue
        }
        const matchingChannel = channelLookup.get(override.entity_key.trim().toLowerCase())
        if (!matchingChannel) {
          continue
        }
        nextTargets[matchingChannel] = override.target_cpa
      }
      setAppliedChannelTargets(nextTargets)
      setTargetCpaDrafts(buildChannelTargetDraftsFromMap(nextTargets))
    }
    setScenarioError(null)
  }

  // ---- Derived data ----

  const nextActionSummary = useMemo(
    () => buildNextActionSummary(scenarioPlan),
    [scenarioPlan]
  )

  const handleExportCsv = useCallback(() => {
    if (!scenarioPlan) {
      return
    }

    const headers = [
      'channel_name',
      'action',
      'current_spend',
      'recommended_spend',
      'spend_delta',
      'spend_delta_percent',
      'current_marginal_cpa',
      'projected_marginal_cpa',
      'confidence_tier',
      'data_quality_state',
      'is_action_blocked',
      'blocked_reason',
      'rationale',
    ]

    const rows = scenarioPlan.recommendations.map((recommendation) => [
      recommendation.channelName,
      recommendation.action,
      recommendation.currentSpend.toFixed(2),
      recommendation.recommendedSpend.toFixed(2),
      recommendation.spendDelta.toFixed(2),
      recommendation.spendDeltaPercent.toFixed(1),
      recommendation.currentMarginalCpa === null ? '' : recommendation.currentMarginalCpa.toFixed(2),
      recommendation.projectedMarginalCpa === null ? '' : recommendation.projectedMarginalCpa.toFixed(2),
      recommendation.confidenceTier,
      recommendation.dataQualityState,
      recommendation.isActionBlocked ? 'true' : 'false',
      recommendation.blockedReason ?? '',
      recommendation.rationale,
    ])

    const csv = [
      headers.join(','),
      ...rows.map((row) => row.map((value) => escapeCsv(value)).join(',')),
    ].join('\n')

    const scenarioLabel = scenarioName.trim() || scenarioPlan.scenarioName
    downloadFile(
      `${sanitizeFileName(scenarioLabel)}.csv`,
      csv,
      'text/csv;charset=utf-8'
    )
  }, [scenarioName, scenarioPlan])

  const handleExportJson = useCallback(() => {
    if (!scenarioPlan) {
      return
    }

    const payload = {
      exported_at: new Date().toISOString(),
      account_id: accountId,
      target_cpa: targetCpa,
      scenario: serializeScenarioPlan(
        scenarioPlan,
        targetCpa,
        buildChannelTargetOverrides(appliedChannelTargets, targetCpa)
      ),
    }

    const scenarioLabel = scenarioName.trim() || scenarioPlan.scenarioName
    downloadFile(
      `${sanitizeFileName(scenarioLabel)}.json`,
      JSON.stringify(payload, null, 2),
      'application/json'
    )
  }, [accountId, appliedChannelTargets, scenarioName, scenarioPlan, targetCpa])

  // ---- Loading state ----
  const loading = accountLoading || analysisLoading
  const error = accountError ?? analysisError

  if (loading) {
    return (
      <div className="space-y-6 animate-pulse">
        <div className="h-4 w-40 rounded bg-slate-200" />
        <div className="card-static p-4 flex items-center justify-between">
          <div className="space-y-2">
            <div className="h-3 w-20 rounded bg-slate-200" />
            <div className="h-2.5 w-48 rounded bg-slate-100" />
          </div>
          <div className="h-9 w-24 rounded-md bg-slate-200" />
        </div>
        <div className="card-static p-6">
          <div className="space-y-2">
            <div className="h-2.5 w-24 rounded bg-slate-200" />
            <div className="h-6 w-64 rounded bg-slate-200" />
          </div>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="space-y-6">
        <Link href="/" className="text-sm text-indigo-600 hover:text-indigo-800 transition-colors">
          &larr; Back to Channel Review
        </Link>
        <div className="card-static border-status-red p-6 animate-fade-in">
          <h3 className="font-semibold text-red-800">Error loading data</h3>
          <p className="text-red-600 text-sm mt-1">{error}</p>
          <p className="text-red-500 text-sm mt-3">
            Make sure the backend is running:{' '}
            <code className="bg-red-50 px-1.5 py-0.5 rounded text-xs">uvicorn app.main:app --reload</code>
          </p>
        </div>
      </div>
    )
  }

  if (!loading && !error && channels.length === 0) {
    return (
      <div className="space-y-6">
        <Link href="/" className="text-sm text-indigo-600 hover:text-indigo-800 transition-colors">
          &larr; Back to Channel Review
        </Link>
        <div className="card-static p-8 text-center animate-fade-in max-w-lg mx-auto mt-6">
          <span className="text-5xl block mb-4">&#x1F4CA;</span>
          <h2 className="text-xl font-semibold text-slate-900">No Channel Data Yet</h2>
          <p className="text-sm text-slate-500 mt-2 leading-relaxed">
            Import your marketing data first, then come back here to generate a recommended plan.
          </p>
          <div className="mt-6">
            <Link href="/import" className="btn-primary inline-block">
              Import Marketing Data
            </Link>
          </div>
        </div>
      </div>
    )
  }

  // ---- Main render ----
  return (
    <div className="space-y-6">
      <Link href="/" className="text-sm text-indigo-600 hover:text-indigo-800 transition-colors">
        &larr; Back to Channel Review
      </Link>

      {/* Page heading */}
      <div className="animate-fade-in">
        <p className="text-xs uppercase tracking-[0.12em] text-indigo-500 font-semibold">
          Scenario Planner
        </p>
        <h1 className="text-2xl font-semibold text-slate-900 mt-1">
          Generate Recommended Plan
        </h1>
      </div>

      {/* Target CPA bar */}
      <div className="card-static p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 animate-fade-in">
        <div>
          <label htmlFor="plan-target-cpa-input" className="text-xs uppercase tracking-wide text-slate-500 font-semibold">
            Target CPA
          </label>
          <p className="text-xs text-slate-400 mt-0.5">
            Determines all traffic lights and scenario recommendations
          </p>
        </div>
        <div className="flex items-center gap-2">
          <span className="text-sm text-slate-500">$</span>
          <input
            id="plan-target-cpa-input"
            type="number"
            min={1}
            step={1}
            value={targetCpa}
            onChange={(e) => {
              const parsed = Number(e.target.value)
              setTargetCpa(Number.isFinite(parsed) && parsed > 0 ? parsed : DEFAULT_TARGET_CPA)
            }}
            className="w-24 rounded-md border border-slate-300 px-3 py-2 text-sm text-slate-800 text-right focus:outline-none focus:ring-2 focus:ring-indigo-200"
          />
        </div>
      </div>

      {/* "What To Do Now" banner */}
      {scenarioPlan && nextActionSummary && (
        <div className="card-static border-l-4 border-indigo-500 p-5 animate-fade-in">
          <div className="flex items-start gap-3">
            <span className="text-lg mt-0.5">&#x1F3AF;</span>
            <div className="flex-1">
              <p className="text-xs uppercase tracking-[0.12em] text-indigo-500 font-semibold">
                What To Do Now
              </p>
              <p className="text-base font-medium text-slate-900 mt-1">{nextActionSummary}</p>
              <p className="text-sm text-slate-500 mt-1">
                Projected net delta: {scenarioPlan.projectedSummary.totalSpendDelta >= 0 ? '+' : ''}
                ${formatMoney(Math.abs(scenarioPlan.projectedSummary.totalSpendDelta), 0)}/day
              </p>
              <div className="flex items-center gap-3 mt-3">
                <button
                  type="button"
                  onClick={handleExportCsv}
                  className="text-sm font-medium text-slate-600 hover:text-slate-800 transition-colors"
                >
                  Export Plan CSV
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
      {!scenarioPlan && scenarioLoading && channels.length > 0 && (
        <div className="card-static border-l-4 border-slate-200 p-5 animate-fade-in">
          <p className="text-sm text-slate-400">Generating recommended plan...</p>
        </div>
      )}

      {/* Scenario Action Center */}
      <div className="card-static p-6 animate-fade-in">
        <ScenarioActionCenter
          channels={channels}
          plannerEnabled={Boolean(accountId)}
          targetCpaDrafts={targetCpaDrafts}
          onTargetCpaDraftChange={handleChannelTargetDraftChange}
          onApplyTargetCpas={handleApplyTargetCpas}
          targetCpaApplying={targetCpaApplying}
          targetCpaError={targetCpaError}
          budgetDeltaPercent={budgetDeltaPercent}
          onBudgetDeltaPercentChange={setBudgetDeltaPercent}
          lockedChannels={lockedChannels}
          onToggleLockedChannel={handleToggleLockedChannel}
          onGenerateScenario={handleGenerateScenario}
          onRefreshSavedScenarios={() => void loadSavedScenarios()}
          scenarioLoading={scenarioLoading}
          scenarioError={scenarioError}
          scenarioPlan={scenarioPlan}
          scenarioName={scenarioName}
          onScenarioNameChange={setScenarioName}
          onSaveScenario={handleSaveScenario}
          scenarioSaving={scenarioSaving}
          saveConfirmation={saveConfirmation}
          savedScenarios={savedScenarios}
          selectedScenarioId={selectedScenarioId}
          onSelectScenario={handleSelectScenario}
          nextActionSummary={nextActionSummary}
          onExportCsv={handleExportCsv}
          onExportJson={handleExportJson}
        />
      </div>
    </div>
  )
}
