'use client';

import { useState } from 'react';
import CsvUploader from '../../components/CsvUploader';
import { Card, Title, Text } from '@tremor/react';

export default function ImportPage() {
    // Hardcoded account ID for local-first MVP. 
    // In a real app, this would come from auth context or URL param.
    // Using the account ID generated by the seed script.
    const [accountId] = useState('95bbc1c9-2535-49ea-9474-dbfa082feee4');

    // Use environment variable for download link
    const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

    return (
        <main className="space-y-6">
            <div className="mb-8">
                <h1 className="text-2xl font-bold text-gray-900">Import Marketing Data</h1>
                <p className="text-gray-500 mt-2">
                    Upload your historical marketing spend and revenue data to generate efficiency curves.
                </p>
            </div>

            <CsvUploader accountId={accountId} />

            <Card>
                <Title>CSV Format Requirements</Title>
                <Text className="mt-2 text-gray-500">
                    Your CSV file must include the following headers (case-sensitive):
                </Text>

                <div className="mt-4 bg-gray-50 p-4 rounded-md border border-gray-200 font-mono text-sm overflow-x-auto">
                    date,channel_name,spend,revenue,[impressions]
                </div>

                <ul className="mt-4 list-disc list-inside text-sm text-gray-600 space-y-2">
                    <li><strong>date:</strong> YYYY-MM-DD format (e.g., 2025-01-31)</li>
                    <li><strong>channel_name:</strong> Name of the marketing channel</li>
                    <li><strong>spend:</strong> Daily spend amount (numeric, no currency symbols)</li>
                    <li><strong>revenue:</strong> Daily attributed revenue (numeric, no currency symbols)</li>
                    <li><strong>impressions:</strong> (Optional) Number of impressions</li>
                </ul>

                <div className="mt-6">
                    <a
                        href={`${apiUrl}/api/import/template`}
                        className="text-blue-600 hover:text-blue-800 font-medium text-sm flex items-center hover:underline"
                    >
                        📥 Download example CSV template
                    </a>
                </div>
            </Card>

            <div className="text-xs text-gray-400 mt-8">
                Account ID: {accountId}
            </div>
        </main>
    );
}
